FROM python:3.9-slim

# # Install necessary tools
# RUN apt-get update && \
#     apt-get install -y --no-install-recommends \
#     wget \
#     ca-certificates \
#     && rm -rf /var/lib/apt/lists/*


RUN apt-get update \
    && apt-get install -y openjdk-17-jdk \
    && pip install pyspark

WORKDIR /app

# CMD ["python"]